spring:
  profiles: default

spring.datasource.default:
	driverClass: com.mysql.jdbc.Driver
	dialect: org.hibernate.dialect.MySQLDialect
	url: jdbc:mysql://localhost:3306/iot
	username: root
	password: 